# Generated by Django 2.0.2 on 2018-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap3_2_1', '0002_auto_20180225_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
