# Generated by Django 2.0.2 on 2018-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap3_2_1', '0008_auto_20180225_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagramuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(to='chap3_2_1.Instagramuser')),
            ],
        ),
    ]
