# Generated by Django 2.0.2 on 2018-02-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chap3', '0004_auto_20180225_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.AlterField(
            model_name='food',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chap3.PersonA'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chap3.PersonA'),
        ),
    ]
