# Generated by Django 2.0.2 on 2018-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chap3', '0006_auto_20180225_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nearby_places',
            field=models.ManyToManyField(related_query_name='near_restaurant', to='chap3.Place'),
        ),
    ]
